# el archivo docker-compose.yml es el archivo de configuración de la aplicación

# declarar la configuración de la aplicación
services: # servicios que se van a utilizar
  web-server: # nombre del servicio
    build: # configuración de la imagen
      context: . # contexto de la imagen
      dockerfile: Dockerfile # archivo Dockerfile
    volumes:
      - .:/app # mapeo de volúmenes, para que los cambios en el código se reflejen en el contenedor
    ports:
      - "8000:8000" # mapeo de puertos, para que el contenedor sea accesible desde el host